services:
  mongo:
    image: mongo:7
    container_name: greenparty-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: "123456"
    volumes:
      - greenparty-mongo:/data/db
    restart: unless-stopped

  greenparty-forum:
    build: .
    container_name: greenparty-forum
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      DB_FILE: "/data/db.json"
      MONGODB_URI: "mongodb://admin:123456@mongo:27017/greenparty?authSource=admin"
      ADMIN_USER: "adminxxx"
      ADMIN_PASSWORD: "2430350396"
    volumes:
      - greenparty-data:/data
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  greenparty-data:
  greenparty-mongo:
